title: Simrit Dhanjal
description: >- # this means newline insensitive in YAML
  Personal website and blog about technology, AI, and software development.
baseurl: "" # for user site, keep empty
url: "https://simritdhanjal.github.io" # your GitHub Pages URL

theme: minima  # simple theme, customizable
plugins:
  - jekyll-feed # for RSS feed

markdown: kramdown